### ISSUE TITLE
implicit stack cleanup

### ISSUE THREAD

**Issue by fgmccabe** [soil-initiative/stacks#3]
Somewhat worried by the implicit cleanup implied by dropping a stack. Would prefer that that be arranged differently (e.g., by forcing an `abort` event on the dropped stack).

**Comment by RossTate** [comment]
If an exception is thrown while a linear reference to the stack is on the stack, there is no (reasonable) way to force an explicit abort. Similarly, a `br` can jump to a label even with a reference to the stack on the stack, and you'd have to remove the frame rule to prevent that. So WebAssembly already requires (at least without substantial changes) all types to be *affine*, meaning implicitly droppable. (Technically, I should be calling `leafref` and `stackref` affine types, but I wanted to emphasize that dropping, even though done implicitly, has observable (from a resource/timing perspective) effects.)

**Comment by RossTate** [comment]
Was this addressed?

**Comment by fgmccabe** [comment]
I see the problem. I suggest closing for now.
